name: raycast
description: A sample command-line application with basic argument parsing.
version: 0.0.1
environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  args: ^2.7.0

dev_dependencies:
  test: ^1.25.6
  very_good_analysis: ^10.0.0
